export const data=[
    {
      "id": 1,
      "name": "Art in the Park",
      "location": "Central Park, New York",
      "date": "2024-11-05",
      "time": "10:00 AM - 5:00 PM",
      "description": "A day-long art festival featuring local artists, live music, and interactive workshops. Free entry.",
      "category": "Art & Culture",
      "organizer": "City Arts Foundation",
      "contact": "info@cityartsfoundation.com",
      "image":"https://media.gettyimages.com/id/1428398435/photo/two-young-female-artists-creating-outdoor-mural.jpg?s=612x612&w=0&k=20&c=FjiGnApUFkV8mbR94TFlwfXu9lsL1oab_FF_f8sBOyU=",
      "genre":"Art"
    },
    {
      "id": 2,
      "name": "Farmers' Market",
      "location": "Union Square, New York",
      "date": "2024-11-12",
      "time": "8:00 AM - 2:00 PM",
      "description": "Enjoy fresh produce, artisanal goods, and delicious treats from local vendors.",
      "category": "Food & Drink",
      "organizer": "Local Farms Association",
      "contact": "market@localfarms.org",
      "image":"https://media.gettyimages.com/id/963914028/photo/boise-farmers-market.jpg?s=612x612&w=0&k=20&c=wPm7uAdawJFt7c_sh2ZeSvTz0Zr3LYaiDWLL_0XYZMk=",
      "genre":"Market"
    },
    {
      "id": 3,
      "name": "Tech Meetup NYC",
      "location": "Tech Hub NYC, Manhattan",
      "date": "2024-11-15",
      "time": "6:00 PM - 9:00 PM",
      "description": "Network with tech enthusiasts and professionals, featuring talks from industry leaders.",
      "category": "Technology",
      "organizer": "Techies NYC",
      "contact": "events@techiesnyc.com",
      "image":"https://media.gettyimages.com/id/912357572/photo/a-apple-macintosh-plus-computer-is-seen-running-a-version-of-the-famous-pac-man-game-warsaw.jpg?s=612x612&w=0&k=20&c=Wfu0PXLU9PFuOdmmAwJPRAfbmje6mf-5ANhaBFmedVU=",
      "genre":"Tech"
    },
    {
      "id": 4,
      "name": "Food Truck Fiesta",
      "location": "Downtown Brooklyn",
      "date": "2024-11-20",
      "time": "11:00 AM - 7:00 PM",
      "description": "An array of food trucks offering flavors from around the world, with live music and outdoor seating.",
      "category": "Food & Drink",
      "organizer": "NY Food Trucks Association",
      "contact": "info@nyfoodtrucks.com",
      "image":"https://media.gettyimages.com/id/1703275538/photo/autumnal-carnival-in-town-street-food-festival-with-cafes-and-entertainment-tents-work-in.jpg?s=612x612&w=0&k=20&c=0b95CL9YFtBpxoDgEWdSHaCv66Z_KUVsVjbCWZlPy50=",
      "genre":"Food Carnival"
    },
    {
      "id": 5,
      "name": "Holiday Craft Fair",
      "location": "Greenwich Village, New York",
      "date": "2024-12-01",
      "time": "9:00 AM - 4:00 PM",
      "description": "Find unique handmade gifts, holiday decorations, and artisanal crafts.",
      "category": "Shopping",
      "organizer": "Village Crafts",
      "contact": "crafts@villagecrafts.com",
      "image":"https://media.gettyimages.com/id/1176156220/photo/tourist-buying-at-craft-fair-in-olinda-pernambuco.jpg?s=612x612&w=0&k=20&c=CY1JcpfhPpzremLiCNcZzTMlMRr2bL2BOR1f7a2CXU0=",
      "genre":"Village Fair"
    },
    {
      "id": 6,
      "name": "Yoga in the Park",
      "location": "Battery Park, New York",
      "date": "2024-12-05",
      "time": "7:30 AM - 8:30 AM",
      "description": "Start your day with a refreshing yoga session by the water. All levels welcome. Free entry.",
      "category": "Health & Wellness",
      "organizer": "NYC Parks",
      "contact": "yoga@nycparks.org",
      "image":"https://media.gettyimages.com/id/1422802905/photo/group-of-six-people-mixed-age-people-making-yoga-pose-in-public-park-in-city-for-fitness.jpg?s=612x612&w=0&k=20&c=yy8gVnX-81Ul9vY8V0Ii0VXST2qIuaDxv-icFW37XZ4=",
      "genre":"Health Concious"
    },
    {
      "id": 7,
      "name": "Film Screening: Classic Cinema Night",
      "location": "The Metro Theater, New York",
      "date": "2024-11-28",
      "time": "7:00 PM - 10:00 PM",
      "description": "Enjoy a classic black-and-white film screening with refreshments. Limited seating available.",
      "category": "Film",
      "organizer": "Classic Films NYC",
      "contact": "screenings@classicfilmsnyc.com",
      "image":"https://media.gettyimages.com/id/452316370/photo/london-england-members-of-the-public-watch-an-outdoor-screening-of-the-film-jaws-in-brockwell.jpg?s=612x612&w=0&k=20&c=YoSIRVvm7V0hCIWzePWmoTHtphSDk48MyHZ_fR2muhw=",
      "genre":"Entertainment"
    },
    {
      "id": 8,
      "name": "Jazz Night",
      "location": "The Blue Note Jazz Club, New York",
      "date": "2024-11-25",
      "time": "8:00 PM - 11:00 PM",
      "description": "An evening of smooth jazz performances by local jazz bands.",
      "category": "Music",
      "organizer": "Blue Note Music Group",
      "contact": "contact@bluenote.com",
      "image":"https://media.gettyimages.com/id/1050875392/photo/rock-n-roll-drummer-at-the-stage.jpg?s=612x612&w=0&k=20&c=HU7O2-_C4s9pAwvVKQ0GbYuPXSKPRLIa6tk0-AVxQs4=",
      "genre":"Entertainment"
    },
    {
      "id": 9,
      "name": "Winter Wonderland Market",
      "location": "Bryant Park, New York",
      "date": "2024-12-10",
      "time": "10:00 AM - 8:00 PM",
      "description": "Holiday market with a variety of vendors, food stalls, and ice skating.",
      "category": "Shopping",
      "organizer": "Bryant Park Events",
      "contact": "events@bryantpark.org",
      "image":"https://media.gettyimages.com/id/900962138/photo/woman-walking-on-christmas-market.jpg?s=612x612&w=0&k=20&c=UCesovWc7Q-6g8sMjfOg8MZRTpH_ydjIsFj31S4Z0zE=",
      "genre":"Entertainment"
    },
    {
      "id": 10,
      "name": "Book Lovers' Meetup",
      "location": "NYC Public Library, Manhattan",
      "date": "2024-12-12",
      "time": "6:00 PM - 8:00 PM",
      "description": "Join fellow book enthusiasts to discuss recent reads and recommendations.",
      "category": "Literature",
      "organizer": "NYC Public Library",
      "contact": "librarymeetups@nypl.org",
      "image":"https://media.gettyimages.com/id/1149064165/photo/asian-women-are-picking-up-books-on-the-bookshelf-to-prepare-to-back-to-school.jpg?s=612x612&w=0&k=20&c=R15oJfXls8aB9OR4evRFI9ukvyFI6fHKnand6nF0Xqw=",
      "genre":"Book"
    },
    {
      "id": 11,
      "name": "Dance Marathon",
      "location": "Times Square, New York",
      "date": "2024-12-15",
      "time": "12:00 PM - 6:00 PM",
      "description": "Join this dance marathon to support a local charity, with live DJs and dance instructors.",
      "category": "Fitness",
      "organizer": "NYC Dance Community",
      "contact": "dance@nyccommunity.org",
      "image":"https://media.gettyimages.com/id/1243327056/photo/a-couple-dances-tango-as-runners-take-part-in-the-buenos-aires-marathon-in-buenos-aires.jpg?s=612x612&w=0&k=20&c=vhGrs1sDDVsU09eSZRukTym-CqgTdhDTLuqMuFA8Qs0=",
      "genre":"Dance"
    },
    {
      "id": 12,
      "name": "Charity Fun Run",
      "location": "Prospect Park, Brooklyn",
      "date": "2024-11-30",
      "time": "9:00 AM - 12:00 PM",
      "description": "A 5k fun run to support local shelters. Registration required.",
      "category": "Health & Wellness",
      "organizer": "NYC Runners",
      "contact": "info@nycrunners.org",
      "image":"https://media.gettyimages.com/id/508701461/photo/startline-at-the-amsterdam-electric-run.jpg?s=612x612&w=0&k=20&c=QZ7HI5wbIuI2DnYa7dNHhLfg3jIs0XuQLHPflLXeHUY=",
      "genre":"Sports"
    },
    {
      "id": 13,
      "name": "Photography Workshop",
      "location": "Brooklyn Bridge Park, New York",
      "date": "2024-11-18",
      "time": "3:00 PM - 6:00 PM",
      "description": "Learn photography basics with hands-on practice in scenic locations.",
      "category": "Art & Culture",
      "organizer": "NYC Photography Club",
      "contact": "workshops@nycphotoclub.com",
      "image":"https://media.gettyimages.com/id/1224226446/photo/recording-educational-video-tutorial-for-vlog.jpg?s=612x612&w=0&k=20&c=3pE1WxG72LzVTGQLW7CXNM_TiUL0flRvjCS1UOkjFm0=",
      "genre":"Photography"
    },
    {
      "id": 14,
      "name": "Cooking Class: Italian Cuisine",
      "location": "Culinary Institute, Manhattan",
      "date": "2024-11-22",
      "time": "5:00 PM - 8:00 PM",
      "description": "Hands-on class on classic Italian dishes. Limited spots available.",
      "category": "Food & Drink",
      "organizer": "Culinary Academy NYC",
      "contact": "info@culinaryacademynyc.com",
      "image":"https://media.gettyimages.com/id/1417834385/photo/little-girl-cutting-pizza-with-a-pizza-cutter.jpg?s=612x612&w=0&k=20&c=LcZM44i1w9oh-Gegzv520qGvOGypEcPQlJizD5mHCo8=",
      "genre":"Cooking"
    },
    {
      "id": 15,
      "name": "Open Mic Night",
      "location": "Greenpoint Cafe, Brooklyn",
      "date": "2024-11-29",
      "time": "7:00 PM - 10:00 PM",
      "description": "Local talent showcase, open for music, poetry, and stand-up.",
      "category": "Music & Comedy",
      "organizer": "Greenpoint Arts Collective",
      "contact": "events@greenpointarts.org",
      "image":"https://media.gettyimages.com/id/157614042/photo/spotlight-on-the-microphone.jpg?s=612x612&w=0&k=20&c=lI2LW9vovT4xGFVb7Qissc2VNiyf7eY1GYdLHyiu0H8=",
      "genre":"Entertainment"
    },
    {
      "id": 16,
      "name": "Dog Adoption Event",
      "location": "Washington Square Park, New York",
      "date": "2024-12-03",
      "time": "11:00 AM - 3:00 PM",
      "description": "Meet dogs from local shelters ready for adoption. Friendly dogs and families welcome.",
      "category": "Community",
      "organizer": "Animal Rescue NYC",
      "contact": "adopt@animalrescuenyc.com",
      "image":"https://media.gettyimages.com/id/1147000367/photo/los-angeles-california-wags-and-walks-dogs-also-available-for-adoption-attend-sony-pictures.jpg?s=612x612&w=0&k=20&c=0RvzcP0n5jeQ3T1gzEgIioZPA6eg4VFldbQKqMdzdBA=",
      "genre":"Pet Lover"
    },
    {
      "id": 17,
      "name": "Street Photography Walk",
      "location": "Lower East Side, New York",
      "date": "2024-11-17",
      "time": "2:00 PM - 5:00 PM",
      "description": "Explore the city streets with other photographers and capture the urban scenery.",
      "category": "Photography",
      "organizer": "Street Shooters NYC",
      "contact": "info@streetshooters.com",
      "image":"https://media.gettyimages.com/id/1457298134/photo/crowd-of-people-walking-across-zebra-top-view.jpg?s=612x612&w=0&k=20&c=37_bx6spy5VZ6i4r2mMkXkuqmm8kFj-o_e6zFOpiMEU=",
      "genre":"Photography"
    },
    {
      "id": 18,
      "name": "Annual Christmas Caroling",
      "location": "Rockefeller Center, New York",
      "date": "2024-12-22",
      "time": "6:00 PM - 8:00 PM",
      "description": "Join in the holiday spirit with caroling and festive lights.",
      "category": "Music & Holiday",
      "organizer": "NYC Carolers Association",
      "contact": "contact@nyccarolers.org",
      "image":"https://media.gettyimages.com/id/593275584/photo/a-large-mob-of-bawdy-santas-pose-for-a-group-photograph-and-sing-their-own-unique-christmas.jpg?s=612x612&w=0&k=20&c=wT7VJvJ8UxJPauUPJSxFbKc-PTI_637zYL7ClRqBbTw=",
      "genre":"Village Fair"
    }
  ]